//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        public int Id { get; set; }
        public int Relacionado { get; set; }
        public string Nombre { get; set; }
        public string Ubicacion { get; set; }
        public string TodoDia { get; set; }
        public string Fecha { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Relacionado Relacionado1 { get; set; }
    }
}
