//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Logica.Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbGeneralEntities : DbContext
    {
        public dbGeneralEntities()
            : base("name=dbGeneralEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EstadoTarea> EstadoTarea { get; set; }
        public virtual DbSet<PosibleCliente> PosibleCliente { get; set; }
        public virtual DbSet<Prioridad> Prioridad { get; set; }
        public virtual DbSet<Tarea> Tarea { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
        public virtual DbSet<Relacionado> Relacionado { get; set; }
    }
}
